### ISSUE TITLE
Hidden Warps with permission can be used from every user

### ISSUE THREAD

**Issue by erikzimmermann** [erikzimmermann/WarpSystem-Code#146]
"thanks, also i'm trying to setup permissions but no matter what, even if all warps have permissions and hidden, anyone without the permission can use it."

**Comment by TKwSni** [comment]
Did this fix work for you? because the permission still doesn't apply in my server, I'm using Luck Perms

**Comment by erikzimmermann** [comment]
Sorry, I didn‘t understand you.

You mean all users can use it from /warp, right?

**Comment by TKwSni** [comment]
for example, you create a new warp in /warps, named Shop

if you add a permission to this warp and the player doesnt have the permission, this will only dissapear from the gui, but if the players types /warp shop, it will teleport him, and that shouldnt be that way, it should deny the warp

**Comment by erikzimmermann** [comment]
Yeah, thanks 👍🏻
I will fix this
