### ISSUE TITLE
Suggestion /server command in warps

### ISSUE THREAD

**Issue by TKwSni** [erikzimmermann/WarpSystem-Code#157]
Version: 3.1.1
Minecraft-Version: 1.12.2
Server-Oparating-System: Linux
_________________________________

Give the ability to be able to create a warps that is basically the bungee command /server, without  giving the permission to the /server command, which is different to a global warp.

basically a server switcher icon, with all the customization features of your plugin

**Comment by erikzimmermann** [comment]
You mean a Icon, which can be placed in the hotbar, where user can switch between servers?

**Comment by TKwSni** [comment]
An icon in the warp gui, that looks like a normal warp but its a server switcher

**Comment by erikzimmermann** [comment]
Wouldn't it be better, when you can configure it in the config.yml?

**Comment by TKwSni** [comment]
how ?

**Comment by erikzimmermann** [comment]
Edit slot and material in the config...

Wait, do you want a item in the hotbar of every player, to switch the servers? Something like a compass?

I didn't understand you ^^

**Comment by TKwSni** [comment]
Nope.

What I mean is let us create an icon inside the /warps gui , exactly like every other warp or gw, but instead of a warp to exact coordinates or world it excecutes the bungeecord /server command, with the delays and all the stuff from your plugin, and switches to the server assigned.

**Comment by erikzimmermann** [comment]
I can do it so, that you can add commands to icons, which will be executed on the bungeecord from that player, which clicks on the button.

This would be contain your idea, am I right?

**Comment by erikzimmermann** [comment]
For that you could create deco icons and add there a command. But currently you can just add local commands. Commands, which are run by the local spigot server

**Comment by TKwSni** [comment]
hmm true, i forgot about that, but those commands dont work for bungeecord right? if you make it work with bungee that will do i think

**Comment by erikzimmermann** [comment]
Ok, that would be easy I think. I try to upload it tomorrow ;)

**Comment by TKwSni** [comment]
Just one thing I just found about this, I need to give players permission to run /server command for this to work, is it possible to make some commands run without permission? bukkit and bungee side ?
