### ISSUE TITLE
Temporarily warps

### ISSUE THREAD

**Issue by xTreMeDani** [erikzimmermann/WarpSystem-Code#186]
Hi, I would like to make a suggestion and that could be very good

This is to implement (if possible) warps that are generated for a limited time, for example, that a user paying a certain amount of money with for example Vault can obtain a public / private warp for a limited time.
This would be the command to give an example: / temporalwarp n name time
And that depends on the time of the warp a certain amount of money is paid

I think it would be a good implementation
regards

**Comment by erikzimmermann** [comment]
Hey, thanks for your contribution!

My questions:

This warp could not be displayed in the warp gui, would this be ok?
I think the cmd is too long, what's with: /tempwarp <create, delete, update>?

- create: opens a gui, where you can edit the time and see that costs
- delete: delete the warp and get money for the remaining time back
- update: update the position of a warp

Players could warp then with /warp <name>

**Comment by xTreMeDani** [comment]
Hello, first of all, say thank you for responding quickly :)

And speaking of the subject, I do not know if I understood well, but you mean that I would not enter the GUI since it does not fit? If so, there would be no problem, with a system either by command or by GUI would be quite good on the implementation, obviously if I misunderstood and fits within the GUI would also be great, but otherwise, there would be no problem.
Secondly, about the command, yes, it would be fine with / tempwarp
The / tempwarp <create, delete, update> <name> <time> could be considered

Then, I do not know how you would do for the price of the X time and how you would carry it out, but it would be good if there was a minimum time (that you assign it in the config) for example of 1d and that the price is also assigned within the config , for example 1d = 1024 $ (it is an example).
And finally it would be nice if you can use the warp publicly or privately, that is, there are two forms of command that would tell you an example right now of each one (obviously they are examples and you develop it as you wish.

Example of private use -> / tempwarp <create, delete, update> <time>
In this way, without obtaining a name, it would be for private use, since it could be used, for example, only by the person who created it.

Example of public use -> / tempwarp <create, delete, update> <name> <time>
In this way, having a name, they can access it publicly if they have paid a certain amount of money for time, if they wish.

Thank you very much for attending, I hope response :)

**Comment by erikzimmermann** [comment]
"Example of private use -> / tempwarp <create, delete, update> 
In this way, without obtaining a name, it would be for private use, since it could be used, for example, only by the person who created it.

Example of public use -> / tempwarp <create, delete, update> 
In this way, having a name, they can access it publicly if they have paid a certain amount of money for time, if they wish."

Both commands are equal ^^


Regarding the warp gui...
The warp gui should be edited only from admins or team members, because if all players can add there own warps, then it goes unstructured... Then it's looks like a mess, because not everybody try to add a warp to beautify your gui ^^. So I thougt I could better create another section for these temporarily warps.

**Comment by xTreMeDani** [comment]
Sorry I forgot the name in the public xD

It would become like this:

"Example of private use -> / tempwarp <create, delete, update> time
In this way, without obtaining a name, it would be for private use, since it could be used, for example, only by the person who created it.

Example of public use -> / tempwarp <create, delete, update> name time
In this way, having a name, they can access it publicly if they have paid a certain amount of money for time, if they wish."

**Comment by erikzimmermann** [comment]
All warps must have names ^^

How would you go to a unnamed warp? :D

**Comment by xTreMeDani** [comment]
Suppose it is as I say, the publics that are those that have a name in front of other people, would have a list with such temporary warps, say for example / tempwarp list (that shows the list of active temporary warps)
And that said people who want to go to that tempwarp go with their name, for example / tw test

And for the case of temporary private warp, it would only be with / tempwarp, that is, they put / tempwarp and they teleport to their private warp (which obviously follows the same rule of money that was previously stated)

**Comment by erikzimmermann** [comment]
Try to start develop this tomorrow

**Comment by erikzimmermann** [comment]
If you could just teleport with /tempwarp, then you could create only one private warp...

I will add this like /tempwarp create <name> (then there will open a gui where you can set public/private and duration)

Furthermore players could create warps above lava. Should warps be protected? So for example if you want to create a warp in lava, the plugin says "hey, your warp has to be on a save platform" or sth like that?

**Comment by xTreMeDani** [comment]
Obviously, I took that for granted at the time I made the suggestion

But I see that I was wrong xD, well I would say that it can not be done. Only in blocks where the backup is safe so to speak

**Comment by xTreMeDani** [comment]
And I see well your option that you can choose in the interface, as long as it's as I said before, that they are temporary and that you have to pay X amount of money to create it

And it would be good to have a pre-established minimum time, for example 1d, because if you think about it, if you did not have a minimum time, you could use it for 10 seconds for example and then remove it again, so on

And this would be very optional (not of great importance), it would be that for example when a person wants to teleport to the warp of another person who at that moment has it publicly, have to pay X amount of money too, for example $ 15 (from the game, obviously) every time you do tp to X warp public

**Comment by erikzimmermann** [comment]
The creator could set a price for the teleport to his warp. This would be a nice idea ^^

Do you have discord? There I could send you some test jars.
If so, add me (CodingAir#0281)
