### ISSUE TITLE
Permissions für Effekt Portale verschwinden bei /reload oder Neustart des Servers.

### ISSUE THREAD

**Issue by ToastiChron** [erikzimmermann/WarpSystem-Code#226]
Version: #2.0.8#
Minecraft-Version: #1.13.2#
Server-Oparating-System: #Windows#
_________________________________

Expectation:

#Plugin speichert die Permission für das Effekt Portal.#
_________________________________

Actual behavior:

#Plugin speichert die Permission für das Effekt Portal und löscht die Permission sobald der Server reloaded wird.#
_________________________________

Steps to reproduce the problem:

#Ich erstelle ein Effekt Portal, stelle die Permission ein, lade den Server neu und es hat wieder "null" bei den Permissions stehen.#
_________________________________

Error:

#Log produziert keinen Error.#

**Comment by erikzimmermann** [comment]
Danke sehr, ich werde mich darum kümmern!
