### ISSUE TITLE
Suggestions: Update warps Coords and alias per warp

### ISSUE THREAD

**Issue by TKwSni** [erikzimmermann/WarpSystem-Code#246]
Version: 3.1.7
Minecraft-Version:  1.12.2
Server-Oparating-System: Linux
_________________________________

1. Update coordinates of a warp without redoing the warp again.

2. Add alias to a warp, because sometimes people prefer to use /warp nameofwarp

and if warp is named like "Fountain of Youth" they have to type /warp fountain_of_youth which is very long, would be better to add an alias to just use /warp fountain

**Comment by erikzimmermann** [comment]
Players could tab them through the warps. So type "/warp " in and press the tab button on your keyboard.
Another software solution would be: If the entered Warp doesn't exist, I search for a warps, which start like the entered name. If there are more than one warps, the plugin could say, that the player have to specify the warp name or something like that.


I think I'll add both ideas ^^

Thank you for your commit!

**Comment by erikzimmermann** [comment]
I'll split them into different issues.
