### ISSUE TITLE
Globalwarps not doing anything

### ISSUE THREAD

**Issue by Stager83** [erikzimmermann/WarpSystem-Code#266]
Version: Latest
Minecraft-Version: 1.13.2
Server-Oparating-System: Linux
_________________________________

Expectation:

When attempting to create a global warp it does nothing, there is also no action in the console either.
For example /globalwarps create Lobby or /globalwarps create Towny command does nothing at all yet all other warpsystem commands work fine. I can check /globalwarps list which is empty.

Error:

There is no error since nothing happens, seems like it is not registering the command?

**Comment by erikzimmermann** [comment]
Did you install the WarpSystem on your BungeeCord?

**Comment by Stager83** [comment]
No, I will do that now if I need to?

**Comment by Stager83** [comment]
I have installed it on my bungeecord and it is working, many thanks! Now to try and find a way to get it to work alonside another warp plugin that was setup on one of the servers as part of the setup I think the command /warps is going to collide

**Comment by erikzimmermann** [comment]
If you're using my plugin there, my plugin will block the command of your warp plugin. But if you don't need my warp function (/warp | /warps) then go into my config.yml and turn warps off.

**Comment by erikzimmermann** [comment]
If you're troubling with something of my plugin, then contact me on discord (CodingAir#0281)
