### ISSUE TITLE
Request: Mechanism to consume an item when using a warp

### ISSUE THREAD

**Issue by phemmer** [erikzimmermann/WarpSystem-Code#277]
This is a feature request for a mechanism which would allow the server to consume an item to use a warp (just warps, not portals).
In my case, I'd like the use of a warp to consume an ender pearl.

I can think of 2 mechanisms for doing this. 1) have WarpSystem support this feature natively in the configuration. 2) Add cancellable events when a warp is used, with which the server admin could use something like Skript or TriggerReactor to handle the functionality.

**Comment by erikzimmermann** [comment]
I think, I'll write an API.

**Comment by phemmer** [comment]
If by "API" you mean something requiring native java code to use, my feedback on that would be that it would have a high barrier of use. I suck at java. This was the reason behind the event idea. A simple skript would be able to hook onto it.

**Comment by erikzimmermann** [comment]
I mean events like PlayerWarpEvent and so on...

**Comment by phemmer** [comment]
Wow, that was fast turnaround. I'll try to get some time this evening to play around with it, and throw a donation your way.

Thanks!

**Comment by erikzimmermann** [comment]
Contact me on discord (CodingAir # 0281) if you have questions
