### ISSUE TITLE
[Feature Request] Warp Sichtbarkeit

### ISSUE THREAD

**Issue by MysticCity** [erikzimmermann/WarpSystem-Code#31]
Eine Option Partikel anzeigen zu lassen an den Ziel Coordinaten des Warps.
Natürlich pro Warp einstellbar ob oder ob nicht.

**Comment by erikzimmermann** [comment]
Also eine Animation, die kommt, nachdem man sich teleportiert hat?
Sowas wie eine Partikeldruckwelle? ^^

**Comment by MysticCity** [comment]
Ja idee ist sehr nice.....
Wäre auch noch nen nettes Feature.

Meine eigendliche Idee wäre aber eher folgende.

Ich Habe einen Warp der an Coordinate x y z geht.
Diesen Warp sieht man ja nicht.
Was manchmal gut ist manchmal aber nicht.
Wenn man nun eine Option hätte Partikel Pro War anzeigen zu lassen würde man wie bei einem Portal dort Partikel sehen nur das es einen eben nicht Teleportiert sondern es der Ankunftspunkt eines Warps ist.

**Comment by erikzimmermann** [comment]
Aber dann sieht das ja aus wie ein Portal. Man müsste etwas machen, das einem Portal nicht direkt ähnelt. Sonst laufen Spieler dort in den Kreis und fragen sich, ob das Plugin eventuell fehlerhaft ist.

**Comment by MysticCity** [comment]
Kann man ja mit dem Hologram machen
Das man reinschreibt Ankuftspunkt oder was auch immer der Owner reinschreiben will.

**Comment by MysticCity** [comment]
Eben so eine art OneWay Portal
Man kommt von einer seite rein (der warp)
aber nicht wieder zurück.

Denn aktuell muss ich noch ein Partikel Plugin verwenden um partikel am Zielpunkt anzeigen zu lassen.

**Comment by erikzimmermann** [comment]
Ok, ich werd versuchen, es umzusetzen. Weiß aber nicht, in welches Update es kommen wird.

**Comment by erikzimmermann** [comment]
Kann nun mit den neuen EffectPortals realisiert werden: einfach am Zielort ein Portal erstellen, welches keine Funktion hat.
