### ISSUE TITLE
[Error] Update Message

### ISSUE THREAD

**Issue by MysticCity** [erikzimmermann/WarpSystem-Code#32]
Ich nutze die Version 2.0.7 trotzdem sagt das Plugin das eine Neue Version verfügbar ist.
Eben Genau diese.

![unbenannt](https://user-images.githubusercontent.com/6275962/36146721-d7329326-10b5-11e8-90c8-26ec6929624c.png)

**Comment by erikzimmermann** [comment]
Ist mit der nächsten Version behoben.
