### ISSUE TITLE
[Change Request] Portal Holo Namen

### ISSUE THREAD

**Issue by MysticCity** [erikzimmermann/WarpSystem-Code#33]
Die Default Frabe für ein Hologram eines Portals ist Rot normalerweise ist es in Minecraft aber Weiß.
Würde flaube ich sin amchen es zu ändern.

Ja ich weis das man Colorcodes nehmen kann.... meinte es auch eher als Default Farbe.

**Comment by erikzimmermann** [comment]
Alles klar
