### ISSUE TITLE
/setwarp not working

### ISSUE THREAD

**Issue by TKwSni** [erikzimmermann/WarpSystem-Code#354]
Version: 3.1.10
Minecraft-Version: 1.13.2, ...
Server-Oparating-System: Linux
_________________________________

Expectation:
Update the selected warp

_________________________________

Actual behavior:

/setwarp returns a  "uknown command" message

I also tried with /editwarp
_________________________________

Error:

No errors on console

**Comment by erikzimmermann** [comment]
Sorry for the late comment, but did you disabled the SimpleWarps?

**Comment by TKwSni** [comment]
Oh I see, I had it disabled... enabling it fixed it.
