### ISSUE TITLE
/warps Error on update 1.12.2 to 1.13.2

### ISSUE THREAD

**Issue by TKwSni** [erikzimmermann/WarpSystem-Code#355]
Version: 3.1.10
Minecraft-Version: 1.13.2, ...
Server-Oparating-System: Linux
_________________________________

Actual behavior:

On /warps, the console throws an error but, /warps work normally
_________________________________

Error:

https://pastebin.com/mEng64BU

**Comment by erikzimmermann** [comment]
Thank you, I'm gonna fix that issue ;)

**Comment by erikzimmermann** [comment]
Do you have a backup of the icon data, you tried to convert to 1.13?

**Comment by TKwSni** [comment]
I'll send to you by discord
